version: '3.10'

services:

 backend:
    build: ./backend

    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn src.start:app --reload --host 0.0.0.0 --port 5000

 frontend:
    depends_on:
      - db
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"

 db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
 postgres_data:
