version: '3.10'

services:

  backend:
    build: ./backend
    # ports:
    #   - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    # ports:
    #   - "5080:3000"
    volumes:
      - '/app/node_modules'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:


volumes:
  postgres_data:
