"""init

Revision ID: 5a6eccacaa96
Revises: 
Create Date: 2024-09-09 10:21:13.408712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6eccacaa96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('main_conditions', sa.String(), nullable=False),
    sa.Column('genre_conditions', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cell'], ['cell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_cell'), 'game', ['cell'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('modifier_dice', sa.Integer(), nullable=True),
    sa.Column('modifier_game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cell'], ['cell.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_cell'), 'player', ['cell'], unique=False)
    op.create_index(op.f('ix_player_user'), 'player', ['user'], unique=False)
    op.create_table('player_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_item_item'), 'player_item', ['item'], unique=False)
    op.create_index(op.f('ix_player_item_user'), 'player_item', ['user'], unique=False)
    op.create_table('session_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session', sa.Uuid(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_user_session'), 'session_user', ['session'], unique=False)
    op.create_index(op.f('ix_session_user_user'), 'session_user', ['user'], unique=False)
    op.create_table('game_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player', sa.Uuid(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_player_game'), 'game_player', ['game'], unique=False)
    op.create_index(op.f('ix_game_player_player'), 'game_player', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_player_player'), table_name='game_player')
    op.drop_index(op.f('ix_game_player_game'), table_name='game_player')
    op.drop_table('game_player')
    op.drop_index(op.f('ix_session_user_user'), table_name='session_user')
    op.drop_index(op.f('ix_session_user_session'), table_name='session_user')
    op.drop_table('session_user')
    op.drop_index(op.f('ix_player_item_user'), table_name='player_item')
    op.drop_index(op.f('ix_player_item_item'), table_name='player_item')
    op.drop_table('player_item')
    op.drop_index(op.f('ix_player_user'), table_name='player')
    op.drop_index(op.f('ix_player_cell'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_game_cell'), table_name='game')
    op.drop_table('game')
    op.drop_table('users')
    op.drop_table('session')
    op.drop_table('item')
    op.drop_table('cell')
    # ### end Alembic commands ###
