export const constants = {
  username: 'superadmin',
  baseUrl: 'http://localhost:5000',
  user: {
    id: 'ae7ee1ee-fade-4c11-afc0-53a702780211',
    logo: 'https://media.tenor.com/MGyRddHl280AAAAM/funnydogs-cute.gif',
  },
  map: {
    defaultImgSrc: 'https://www.w3schools.com/css/img_forest.jpg',
    cells: [
      { id: 0, title: 'test cell ()' },
      { id: 1, title: 'test cell ()' },
      { id: 2, title: 'test cell ()' },
      { id: 3, title: 'test cell ()' },
      { id: 4, title: 'test cell ()' },
      { id: 5, title: 'test cell ()' },
      { id: 6, title: 'test cell ()' },
      { id: 7, title: 'test cell ()' },
      { id: 8, title: 'test cell ()' },
      { id: 9, title: 'test cell ()' },
      { id: 10, title: 'test cell ()' },
      { id: 11, title: 'test cell ()' },
      { id: 12, title: 'test cell ()' },
      { id: 13, title: 'test cell ()' },
      { id: 14, title: 'test cell ()' },
      { id: 15, title: 'test cell ()' },
      { id: 16, title: 'test cell ()' },
      { id: 17, title: 'test cell ()' },
      { id: 18, title: 'test cell ()' },
      { id: 19, title: 'test cell ()' },
      { id: 20, title: 'test cell ()' },
      { id: 21, title: 'test cell ()' },
      { id: 22, title: 'test cell ()' },
      { id: 23, title: 'test cell ()' },
      { id: 24, title: 'test cell ()' },
      { id: 25, title: 'test cell ()' },
      { id: 26, title: 'test cell ()' },
      { id: 27, title: 'test cell ()' },
      { id: 28, title: 'test cell ()' },
      { id: 29, title: 'test cell ()' },
      { id: 30, title: 'test cell ()' },
      { id: 31, title: 'test cell ()' },
      { id: 32, title: 'test cell ()' },
      { id: 33, title: 'test cell ()' },
      { id: 34, title: 'test cell ()' },
      { id: 35, title: 'test cell ()' },
      { id: 36, title: 'test cell ()' },
      { id: 37, title: 'test cell ()' },
      { id: 38, title: 'test cell ()' },
      { id: 39, title: 'test cell ()' },
    ],
  },
  http: {
    ok: 200,
    unauthorized: 401,
    forbidden: 403,
    notFound: 404,

    isInfo: (status) => status > 99 && status < 200,
    isOk: (status) => status > 199 && status < 300,
    isRedirect: (status) => status > 299 && status < 400,
    isBad: (status) => status > 399 && status < 500,
    isSystemBad: (status) => status > 499 && status < 600,
  },
};
